version: "3.7"

services:
  api:
    depends_on:
      - db
    ports:
      - "8000:8000"
    build:
      dockerfile: ./api/Dockerfile
      context: .
    volumes:
      - ./api:/home/user/api
    environment:
      - DB_STRING=postgresql://postgres:test@db:5432/postgres

  db:
    image: postgres:14.5
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/pg_data
    environment:
      - POSTGRES_PASSWORD=test

volumes:
  pg-data:
